### ISSUE TITLE
How to do tooltipExpression

### ISSUE THREAD

**Issue by juanetec** [Servoy/fullcalendarcomponent#13]
Hi,
I try what the wiki say, about tooltipExpression but I do not get it.
This is what the wiki say:
The text expression to be shown as a tooltip when hovering on the calendar events. Use double curly brackets to evaluate {{propertyName}} the event's properties

This is what I try:
 eventSources: [ events: [{ title: "lunch event {{title}}", start: new Date() }]]

where o how could I put the  tooltipExpression?

Un Saludo 

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,
tooltipExpression can be set in the Fullcalendar component itself as a text property. The expression will be evaluated vs the event object hovered.
Example:
"This is the event title:{{title}}. The event starts at: {{start}}. Description: {{data.description}} "

{{title}} will be replaced with the event.title, {{start}} with the event.start value.
You can make use of the custom data property you can add to the event to add custom info to it. Example
eventSources: [ events: [{ title: "lunch event {{title}}", start: new Date(), data: {description: "This is my custom description property"} }]]

Regards,
Paolo
