### ISSUE TITLE
Callback function not return a date, always return null

### ISSUE THREAD

**Issue by leokady** [Servoy/fullcalendarcomponent#2]
When user click on the day control (left calendar) the callback function onDayClick return null. This problem also exist in the Demo Sevoy solution for FullCalendar component. We need to switch right calendar to week view base of selected date on the left calendar. 

A same problem exist on the right calendar. Selected day is null

**Comment by paronne** [comment]
New release with the fix will be available soon

**Comment by paronne** [comment]
The new release of fullcalendar is now available for download.
