### ISSUE TITLE
Drag and drop is not working in IE/Edge

### ISSUE THREAD

**Issue by saleman67** [Servoy/fullcalendarcomponent#7]
The drag and drop option is no longer working in IE, you can also see it on your demo site:
https://demo.servoy.com/solutions/sampleGallery/index.html?f=galleryMain

In servoy 8.1.4 it was working, but in servoy 8.2.2 it is no longer working, so we think it has something todo with a change in servoy.

**Comment by paronne** [comment]
That is an issue of the JQuery library versions shipped by Servoy. The fix requires an update of the JQuery lib. Check the servoy follow up case https://support.servoy.com/browse/SVY-12047

**Comment by paronne** [comment]
Fixes since Servoy 8.2.3
